MilesCranmer/DispatchDoctor.jl

src/DispatchDoctor.jl
test/runtests.jl

Right now the function
```julia
using DispatchDoctor
@stable f(a, t::Type{T}) where {T} = sum(a; init=zero(T))
```
is not classified as stable, even though it is. This is because of weird specialization rules: https://docs.julialang.org/en/v1.10/manual/performance-tips/#Be-aware-of-when-Julia-avoids-specializing
To fix this, this PR moves back to a closure approach. This simplifies a lot of other things too and doesn't hurt performance.
This also makes it possible to use `Vararg`-args.

Fix Julia special case types

---

README.md
src/DispatchDoctor.jl
test/Project.toml
test/runtests.jl

For example:
```julia
@stable module A
using DispatchDoctor: @unstable
@unstable f1() = rand(Bool) ? 0 : 1.0
f2(x) = x
f3(; a=1) = a > 0 ? a : 0.0
end
```
where we use `@unstable` to mark functions that should not be wrapped.
(*Tip: in the REPL, wrap this with `@eval`, because the REPL has special handling of the `module` keyword.*)
This gives us:
```julia
julia> A.f1()
0
julia> A.f2(1.0)
1.0
julia> A.f3(a=2)
ERROR: TypeInstabilityError: Instability detected in function `f3`
with keyword arguments `@NamedTuple{a::Int64}`. Inferred to be
`Union{Float64, Int64}`, which is not a concrete type.
```
where we can see that the `@stable` was automatically applied
to all the functions, except for `f1`.
> [!NOTE]
> This will also automatically be applied to the code
> being added by any `include` …

Add support for module-level `@stable`

---

.github/workflows/CI.yml
Project.toml
README.md
src/DispatchDoctor.jl
test/unittests.jl

@mkitti what do you think?
From the new README:
> 
> You might find it useful to *only* enable `@stable` during unit-testing,
> to have it check every function in a library, but not throw errors for
> downstream users. For this, you can use the `mode` keyword to set the
> default behavior:
> 
> ```julia
> module MyPackage
> using DispatchDoctor
> @stable mode="disable" begin
> 
> # Entire package code
> 
> end
> end
> ```
> 
> This sets the default, but the mode is configurable
> via [Preferences.jl](https://github.com/JuliaPackaging/Preferences.jl):
> 
> ```julia
> using MyPackage
> using Preferences
> 
> set_preferences!(MyPackage, "instability_check" => "error")
> ```
> 
> which you can also set to be `"warn"` if you would just like warnings.
> You might find it useful to set this …

Add preferences interface

---

src/DispatchDoctor.jl
test/unittests.jl

This is so you can use `@code_warntype` on a function definition.
Basically we now put the function body in both the "simulator" function as well as the original function. It uses the simulator to check the inferred type, then just assumes it will have the same thing and returns.
It also renames the generated function to be called "<function name>_simulator" rather than "_closure"

Move body to main function definition

---

docs/src/macros.md
src/DispatchDoctor.jl
test/unittests.jl

@matthias314 I figured out a way to do it!
I also made it the default behavior. You can add custom behaviour with `register_macro!` which I added docs for.

Propagate macros to function definitions

---

src/DispatchDoctor.jl
test/unittests.jl

Basically it just extracts the first `LineNumberNode` in the expression and puts that in the error message/warning message. So even if the Julia backtrace is innaccurate, at least that part is decent.

More accurate source tracking

---

src/macro_interactions.jl
src/stabilization.jl
test/unittests.jl

Propagating macros is uber difficult. This took me nearly six hours of just staring at expressions to fix. (I hope you get some use out of this @matthias314!)
Basically this completely refactors the macro propagation functionality to fix some issues. Everything is immutable so there is less spooky action at a distance. And seems like no more issues because of that more robust approach.
How it works is for any macros
```julia
@stable @macro1 @macro2 option1 option2 @macro3 ... function f(x)
x
end
```
It will aggregate all macros into a stack, like
```
@macro1
@macro2 option1 option2
@macro3
```
If it keeps encountering macros, it will keep accumulating them in the stack. 
Once it either:
1. Encounters an expression that is neither a macro or a function. Then it will discard the stack, …

Fix macro stacking

---

Project.toml
src/utils.jl
test/unittests.jl

Fixes an edge case of `Base.isconcretetype` where `Type{Float32}` will result in `false`.

Fix type of type

---

README.md
src/macros.jl
src/preferences.jl
src/stabilization.jl
test/unittests.jl

Reduces precompilation time increase noted by @thofman
This allows you to set `default_codegen_level="min"` which will avoid duplicating function bodies, without affecting anything else. The reason for the function body duplication is literally just to get `@code_warntype` working, but nothing else.
There is also a Preferences.jl key for it: `instability_check_codegen` (which overrides the default).
With `default_codegen_level="min"`, you can't use `@code_warntype`. So the default is `"debug"`. But if you are building a massive library, I can totally see `"min"` being useful to cut down compilation time.

Add `codegen_level` parameter for minimal codegen

---

README.md
src/DispatchDoctor.jl
src/macros.jl
src/parse_options.jl
src/preferences.jl
src/stabilization.jl
src/utils.jl
test/dynamic_expressions.jl
test/unittests.jl

@ChrisRackauckas is this what you are looking for?
For example:
```julia
@stable default_ignore_union = true begin
f(x) = x > 0 ? x : 0.0
g() = Val(rand())
end
f(0) # No error; just a union
@test_throws TypeInstabilityError g()
```
This doesn't affect any existing code as `ignore_union` is set to true by default. As with other parameters you can configure this with Preferences.jl – `instability_check_ignore_union` is the new parameter here.
As usual this should be removed by the compiler if the code is stable.
Fixes #29. The PR also moves the options parsing to a new file `parse_options.jl`.

Implement mechanism for ignoring unions

---

src/DispatchDoctor.jl
src/utils.jl
test/unittests.jl

Fixes an edgecase where a return type `Tuple{Union{A,B,C}}` would not respect the user-provided `union_limit`. This fixes it by adding special treatment for tuple types.
Note that this does not apply to any other struct. It just seems that tuples get special treatment by the compiler:
```julia
julia> struct A{T}
a::T
end
julia> Base.isconcretetype(Union{Float32,Float64})
false
julia> Base.isconcretetype(Tuple{Union{Float32,Float64}})
false
julia> Base.isconcretetype(A{Union{Float32,Float64}})
true
```

Fix union limit edge-case within tuple

---

src/macro_interactions.jl
test/unittests.jl

Currently we just skip `iterate` but not also `getproperty` and `setproperty!`.
These functions are meant to be unstable with respect to input argument (just a symbol) and will (hopefully) always be inlined by the compiler. So this special cases them.

Skip `getproperty` and `setproperty!`

---

.github/workflows/benchmark_pr.yml
benchmark/Project.toml
benchmark/benchmarks.jl

Just so we can monitor that the macro itself stays speedy and also that load time doesn't increase (especially for `default_mode="disable"` which people will use in packages)

AirspeedVelocity.jl CI + Benchmarks

---

ext/DispatchDoctorChainRulesCoreExt.jl
src/stabilization.jl
test/zygote.jl

The `show_warning` can also be written as
```julia
@non_differentiable show_warning(::Any...)
```
for consistency.

fix zygote incompatibility with warnings

---

src/parse_options.jl
src/preferences.jl
test/FakePackage1/LocalPreferences.toml
test/FakePackage1/Project.toml
test/FakePackage1/src/FakePackage1.jl
test/FakePackage2/LocalPreferences.toml
test/FakePackage2/Project.toml
test/FakePackage2/src/FakePackage2.jl
test/FakePackage3/Project.toml
test/FakePackage3/src/FakePackage3.jl
test/unittests.jl
test/zygote.jl

Surprisingly it takes ~600 us to load from Preferences.jl. This seems to slow down package load times, **even if** `default_mode="disable"`. So this helps speed up Preferences.jl access via caching and an early exit if a `"disable"` is found.
Now it's **under 1 us**!

Cached access to Preferences.jl

---

src/stabilization.jl
src/utils.jl
test/zygote.jl

This uses a `@generated` function on `_promote_op` to fix the precompilation errors on Julia 1.11.
cc @avik-pal. Are you okay with the use of `@generated` here? There is a non-generated branch so I'm fairly confident it won't affect inference or constant propagation at all. I do view this as necessary to fix the segfaults on v1.11 unless we can find a nicer way around them so am content for now.

Fix precompilation on Julia 1.11

---

src/stabilization.jl
src/utils.jl
test/unittests.jl

Fixes #54 
To manage the combinatorial explosion of composite argument expressions, I made `inject_symbol_to_arg` recursive, which means it now also supports `f((; x)::Foo...=foo) = ...` and other deeply cursed incantations. I didn't implement tests for such combinations, however.

Support type-constrained destructuring

---

src/printing.jl
test/unittests.jl

Very minor change that results in the error printing:
```
ERROR: DispatchDoctor.TypeInstabilityError: ...
```
rather than the current behavior which is:
```
ERROR: DispatchDoctor._Errors.TypeInstabilityError: ...
```

docs: clean up printing of error type

---

.github/workflows/CI.yml
Project.toml
src/utils.jl
test/dynamic_expressions.jl
test/unittests.jl

This gets the following code to work correctly:
```julia
@stable default_codegen_level = "min" g_min(_::Int) = 1
@test g_min(1) == 1
```
It seems like the min codegen level was interfering with this.
This also deprecates Julia <1.10 because 1.9 and earlier are now unmaintained.

Fix underscore arguments with `codegen_level="min"`

---

Project.toml
README.md
src/stabilization.jl
src/utils.jl
test/dynamic_expressions.jl
test/unittests.jl

Fixes #59. Now `@nospecialize` methods are ignored.

fix: avoid `@nospecialize` methods

---

Project.toml
src/utils.jl
test/unittests.jl

This "Core.TypeofBottom" type in Julia came up as an edge case in SymbolicRegression.jl testing. We can better deal with such edge cases with the simple check `hasproperty(T, :types)` and otherwise fall back to `Base.isconcretetype`.

fix: behavior for Core.TypeofBottom

---

README.md
src/macros.jl
src/preferences.jl
test/FakePackage1/LocalPreferences.toml

This implements a change of the Preferences.jl option keys:
- `instability_check` => `dispatch_doctor_mode`
- `instability_check_codegen_level` => `dispatch_doctor_codegen_level`
- `instability_check_union_limit` => `dispatch_doctor_union_limit`
However, the old keys will still work - the deprecation is soft. This change to make the names more intuitive for new users. I think I'd like to do 1.0 soon and this is the main change I'd like to get in before then.
@avik-pal @Dale-Black @co1emi11er2 (each of you has registered one or more packages with DispatchDoctor as a dependency) – what do you think? Is this ok with you?

Update preference keys with soft deprecation

---

src/utils.jl
test/unittests.jl

Dealing with https://github.com/JuliaLang/julia/issues/58899 weirdness

fix: deal with unbound args in signature

---

src/stabilization.jl
test/unittests.jl

Basically due to the Julia boxing issue:
```julia
julia> using Test
julia> function f_recursive()
function g(n)
n <= 0 && return 1
return n * g(n - 1)
end
end
f_recursive (generic function with 1 method)
julia> Test.@inferred f_recursive()
ERROR: return type var"#g#13" does not match inferred return type Any
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:35
[2] top-level scope
@ REPL[8]:1
```
we see the same issue when using `@stable` on closure functions because we call
```julia
$(ignore_function)($(func[:name]))
```
So now we use `var"#self#"` to refer to the self function.

fix: issue with closures self-referencing
